// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ocasti/fuego-quazar/topsecret/v1/internal/ctx"
)

// Injectors from wire.go:

func Initialize() (*ctx.Handler, error) {
	handler := providerHandler()
	return handler, nil
}
