service: fq-top-secret-split

frameworkVersion: ${self:custom.active.serverless-version}

custom:
  active:       ${file(../conf.${self:provider.stage}.yml):conf}
  serviceName: top-secret-split

provider:
  name: aws
  runtime: go1.x
  stage:   ${opt:stage, 'dev'}
  region:  us-east-1
  memorySize: 128

  environment:
    DYNAMODB_TABLE:               ${self:custom.active.dynamodb_quasar_fire}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:${self:custom.active.account}:table/${self:custom.active.dynamodb_quasar_fire}
        - arn:aws:dynamodb:${self:provider.region}:${self:custom.active.account}:table/${self:custom.active.dynamodb_quasar_fire}/index/*

resources:
  Resources:
    V1LogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        RetentionInDays: ${self:custom.active.log_retention}

package:
  individually: true
  exclude:
    - ./**

functions:
  v1:
    handler: bin/v1
    package:
      include:
        - ./bin/v1
    events:
      - http:
          path: /topsecret_split/{satellite_name}
          method: post
      - http:
          path: /topsecret_split
          method: get

